WebSistemaVentas/Models/Configuraciones/Perfiles/Get1_Perfiles.cs
namespace WebSistemaVentas.Models.Configuraciones.Perfiles;

public class Get1_Perfiles
{
    public int id { get; set; }
    public string nombre_perfil { get; set; }
    public string descripcion { get; set; }
    public bool estado { get; set; }
    public string auditoria_creacion { get; set; }
}

WebSistemaVentas/Models/Configuraciones/Perfiles/Get2_PerfilXId.cs
namespace WebSistemaVentas.Models.Configuraciones.Perfiles;

public class Get2_PerfilXId
{
    public int id { get; set; }
    public string nombre_perfil { get; set; }
    public string descripcion { get; set; }
    public bool estado { get; set; }
}

WebSistemaVentas/Models/Configuraciones/Perfiles/SetPerfilParametros.cs
namespace WebSistemaVentas.Models.Configuraciones.Perfiles;

public class SetPerfilParametros
{
    public string p_opcion { get; set; }
    public int p_id { get; set; }
    public string p_nombre_perfil { get; set; }
    public string p_descripcion { get; set; }
    public bool p_estado { get; set; }
    public int p_id_usuario { get; set; }
}

WebSistemaVentas/Models/Configuraciones/Usuarios/Get1_Usuarios.cs
namespace WebSistemaVentas.Models.Configuraciones.Usuarios;

public class Get1_Usuarios
{
    public int id { get; set; }
    public string nombre { get; set; }
    public string correo { get; set; }
    public bool estado { get; set; }
    public string auditoria_creacion { get; set; }
}

WebSistemaVentas/Models/Configuraciones/Usuarios/Get2_UsuarioXId.cs
namespace WebSistemaVentas.Models.Configuraciones.Usuarios;

public class Get2_UsuarioXId
{
    public int id { get; set; }
    public string nombre { get; set; }
    public string correo { get; set; }
    public bool estado { get; set; }
}

WebSistemaVentas/Models/Configuraciones/Usuarios/SetUsuarioParametros.cs
namespace WebSistemaVentas.Models.Configuraciones.Usuarios;

public class SetUsuarioParametros
{
    public string p_opcion { get; set; }
    public int p_id { get; set; }
    public int p_id_perfil { get; set; }
    public string p_nombre { get; set; }
    public string p_correo { get; set; }
    public string p_clave { get; set; }
    public bool p_estado { get; set; }
    public int p_id_usuario { get; set; }
}

WebSistemaVentas/Models/ErrorViewModel.cs
namespace WebSistemaVentas.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebSistemaVentas/Models/Mantenimientos/Categorias/Get1_Categorias.cs
namespace WebSistemaVentas.Models.Mantenimientos.Categorias;

public class Get1_Categorias
{
    public string codigo { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }
    public bool estado { get; set; }
    public string auditoria_creacion { get; set; }
}

WebSistemaVentas/Models/Mantenimientos/Categorias/Get2_CategoriasXCodigo.cs
namespace WebSistemaVentas.Models.Mantenimientos.Categorias;

public class Get2_CategoriasXCodigo
{
    public string codigo { get; set; }
    public string nombre { get; set; }
    public string descripcion { get; set; }
    public bool estado { get; set; }
}

WebSistemaVentas/Models/Mantenimientos/Categorias/SetCategoriaParametros.cs
namespace WebSistemaVentas.Models.Mantenimientos.Categorias;

public class SetCategoriaParametros
{
    public string p_opcion { get; set; }
    public string p_codigo { get; set; }
    public string p_nombre_categoria { get; set; }
    public string p_descripcion { get; set; }
    public bool p_estado { get; set; }
    public int p_id_usuario { get; set; }
    
}

WebSistemaVentas/Controllers/ConfiguracionesController.cs
using Microsoft.AspNetCore.Mvc;
using WebSistemaVentas.BLL;
using WebSistemaVentas.Models.Configuraciones.Perfiles;

namespace WebSistemaVentas.Controllers;

public class ConfiguracionesController : Controller
{
    private IConfiguracionesBL _configuracionesBl;

    public ConfiguracionesController(IConfiguracionesBL configuracionesBl)
    {
        _configuracionesBl = configuracionesBl;
    }

    // GET
    public IActionResult RegistrarPerfil()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> SetPerfil(SetPerfilParametros parametros)
    {
        return Ok(await _configuracionesBl.SetPerfil(parametros));
    }
}

WebSistemaVentas/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebSistemaVentas.Models;

namespace WebSistemaVentas.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

WebSistemaVentas/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using WebSistemaVentas.DTO.Login;

namespace WebSistemaVentas.Controllers;

public class LoginController : Controller
{
    //private readonly IHttpContextAccessor _context;

    // public LoginController(IHttpContextAccessor context)
    // {
    //     _context = context;
    // }
    // GET
    public IActionResult Index()
    {
        return View();
    }

    // [HttpPost]
    // public JsonResult Login(LoginDTO login)
    // {
    //     bool estado = false;
    //     string mensaje = "";
    //     string url = "";
    //
    //     try
    //     {
    //     }
    //     catch (Exception e)
    //     {
    //         Console.WriteLine(e);
    //         throw;
    //     }
    // }
}

WebSistemaVentas/Controllers/MantenimientosController.cs
using Microsoft.AspNetCore.Mvc;
using WebSistemaVentas.BLL;
using WebSistemaVentas.Models.Mantenimientos.Categorias;

namespace WebSistemaVentas.Controllers;

public class MantenimientosController : Controller
{
    // GET
    // public IActionResult Index()
    // {
    //     return View();
    // }
    private IMantenimientosBL _mantenimientosBl;

    public MantenimientosController(IMantenimientosBL mantenimientosBl)
    {
        _mantenimientosBl = mantenimientosBl;
    }
    
    #region Vistas

    public ActionResult RegistrarCategoria()
    {
        return View();
    }

    public ActionResult ListarCategorias()
    {
        return View();
    }
    #endregion

    [HttpPost]
    public async Task<ActionResult> SetCategoria(SetCategoriaParametros parametros)
    {
        return Ok(await _mantenimientosBl.SetCategoria(parametros));
    }

    [HttpGet]
    public async Task<ActionResult> GetCategorias()
    {
        return Ok(await _mantenimientosBl.GetCategorias());
    }

    [HttpGet]
    public async Task<ActionResult> GetCategoriaByCodigo(string codigo)
    {
        return Ok(await _mantenimientosBl.GetCategoriasByCodigo(codigo));
    }
    
}

WebSistemaVentas/Views/Configuraciones/ListarPerfiles.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
      
</div>
</body>
</html>

WebSistemaVentas/Views/Configuraciones/ListarUsuarios.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
      
</div>
</body>
</html>

WebSistemaVentas/Views/Configuraciones/RegistrarPerfil.cshtml
@model WebSistemaVentas.Models.Configuraciones.Usuarios.Get1_Usuarios

@section Scripts
{
    <script src="~/js/configuraciones/registrar-perfil.js"></script>
    <script src="~/js/util.js"></script>
    <script src="~/js/core.js"></script>
}

@section Styles{
    <link rel="stylesheet" href="~/css/configuraciones/registrar-perfil.css">
}

<div class="container-fluid">
    <div class="container">
        <div class="formBox">
            <form id="formcrud">
                <div class="row">
                    <div class="col-sm-12">
                        <h1>Registrar Perfil</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <div class="inputBox ">
                            <div class="inputText">ID</div>
                            <input type="text" name="txtid" id="txtid" class="input" disabled>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="inputBox ">
                            <div class="inputText">Perfil</div>
                            <input type="text" name="txtNombrePerfil" id="txtNombrePerfil" class="input" onchange="this.value = this.value.toUpperCase()" onblur="this.value = this.value.toUpperCase()">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="inputBox">
                            <div class="inputText">Descripción</div>
                            <textarea class="input" name="txtDescripcion" id="txtDescripcion" onchange="this.value = this.value.toUpperCase()" onblur="this.value = this.value.toUpperCase()"></textarea>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-check form-switch mb-3">
                        <input class="form-check-input" type="checkbox" role="switch" id="switchestado" checked>
                        <label class="form-check-label" for="switchestado">Estado Activo</label>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-6">
                        <button type="button" id="btnGuardar" class="button">Guardar</button>
                    </div>
                    <div class="col-sm-6">
                        <button type="button" class="button button-danger">Cancelar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

WebSistemaVentas/Views/Configuraciones/RegistrarUsuario.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
      
</div>
</body>
</html>

WebSistemaVentas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@section Scripts
{
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebSistemaVentas/Views/Login/Index.cshtml
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>
<head>
	<title>Login Page</title>
   <!--Made with love by Mutiullah Samim -->
   
	<!--Bootsrap 4 CDN-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <!--Fontawesome CDN-->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

	<!--Custom styles-->
	<link rel="stylesheet" type="text/css" href="~/css/login.css">
</head>
<body>
<div class="container">
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" class="form-control" placeholder="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="#">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>

WebSistemaVentas/Views/Mantenimientos/ListarCategorias.cshtml
@section Scripts
{

    <script src="~/js/mantenimientos/listar-categorias.js"></script>
}

<div class="row g-5">

    <div class="card col-12 col-xl-10 order-1 order-xl-0 p-2 w-100">

        <div class="d-flex flex-wrap mb-2">
            <a class="btn btn-primary btn-sm p-2" asp-controller="Mantenimientos" asp-action="RegistrarCategoria">
                <span class="fa fa-plus-circle"></span> Nuevo
            </a>
        </div>
     
        <div id="tabla-elementos">
            <div class="search-box mb-3 mx-auto">
                <form class="position-relative" data-bs-toggle="search" data-bs-display="static">
                   <div class="input-group w-25">
                     <input class="form-control search-input search form-control-sm" type="search" placeholder="Buscar" aria-label="Buscar"/>
                     <div class="input-group-append">
                       <span class="fa fa-search input-group-text"></span>
                     </div>
                   </div>
                </form>
            </div>
            <div class="table-responsive">
            <table class="table table-sm fs--1 mb-0">
                <thead id="tblhead-elementos">
                </thead>
                <tbody class="list" id="tblbody-elementos">
                </tbody>
            </table>
            </div>
            <div class="d-flex justify-content-center mt-3">
                <ul class="mb-0 pagination">
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="edit-modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Editar</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body">
                <form>
                    <div class="mb-3">
                        <label id="lbl-id-cod" for="id-or-cod" class="col-form-label"></label>
                        <input type="text" class="form-control" id="id-or-cod" disabled>
                    </div>
                    <div class="mb-3">
                        <label id="lbl-nombre-element" for="nombre-categoria" class="col-form-label"></label>
                        <input type="text" class="form-control" id="nombre-categoria" onchange="this.value = this.value.toUpperCase()" onblur="this.value = this.value.toUpperCase()">
                    </div>
                    <div class="mb-3">
                        <label id="lbl-texto-1" for="texto-ad-1" class="col-form-label"></label>
                        <textarea type="text" class="form-control" id="texto-ad-1" rows="3" style="resize: none" onchange="this.value = this.value.toUpperCase()" onblur="this.value = this.value.toUpperCase()"> </textarea>
                    </div>
                    <div class="form-check form-switch mb-3">
                        <input class="form-check-input" type="checkbox" role="switch" id="switchestado" checked>
                        <label class="form-check-label" for="switchestado">Estado Activo</label>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="btnGuardarElement">Guardar</button>
            </div>
        </div>
    </div>
</div>

WebSistemaVentas/Views/Mantenimientos/RegistrarCategoria.cshtml
@section Styles
{
}

@section Scripts{
    <script src="~/js/mantenimientos/registrar-categoria.js"></script>
}


<form id="formcrud" class="mb-9">
    <div class="mb-3">
        <label for="txtcodigo" class="form-label">CODIGO</label>
        <input type="text" class="form-control" id="txtcodigo" disabled>
    </div>
    <div class="mb-3">
        <label for="txtnombreCategoria" class="form-label">Nombre:</label>
        <input type="text" class="form-control" id="txtnombreCategoria" onchange="this.value=this.value.toUpperCase()" onblur="this.value=this.value.toUpperCase()" placeholder="Ejemplo: Lacteos">
    </div>

    <div class="mb-3">
        <label for="txtDescripcion" class="form-label">Descripcion</label>
        <input type="text" class="form-control" id="txtDescripcion" onchange="this.value = this.value.toUpperCase()" onblur="this.value=this.value.toUpperCase()">
    </div>
    <div class="form-check form-switch mb-3">
        <input class="form-check-input" type="checkbox" role="switch" id="switchestado" checked>
        <label class="form-check-label" for="switchestado">Estado Activo</label>
    </div>

    <button id="btnguardar" type="button" class="btn btn-primary btn-sm me-2">Guardar</button>
    <a type="button" class="btn btn-danger btn-sm" asp-controller="Mantenimientos" asp-action="ListarCategorias">Cancelar</a>
</form>

WebSistemaVentas/Views/Shared/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebSistemaVentas</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
                    @* </li> *@
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
                    @* </li> *@

                    <div class="btn-group">
                        <button class="btn dropdown-toggle" type="button" id="mantenimientos-dd" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">
                            <span class="fa fa-list"></span> Mantenimientos
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="mantenimientos-dd">
                            <li>
                                <div class="btn-group dropend w-100">
                                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" onclick="event.stopPropagation();">
                                        Categorías
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" asp-controller="Mantenimientos" asp-action="RegistrarCategoria">Registrar</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-controller="Mantenimientos" asp-action="ListarCategorias">Listar</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item text-center" href="#">Menu item</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item text-center" href="#">Menu item</a>
                            </li>
                        </ul>
                    </div>

                    <div class="btn-group">
                        <button class="btn dropdown-toggle" type="button" id="mantenimientos-dd" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">
                            <span class="fa fa-gears"></span> Configuraciones
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="mantenimientos-dd">
                            <li>
                                <div class="btn-group dropend w-100">
                                    <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" onclick="event.stopPropagation();">
                                        Perfiles
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="dropdown-item" asp-controller="Configuraciones" asp-action="RegistrarPerfil">Registrar</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" asp-controller="Configuraciones" asp-action="">Listar</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item text-center" href="#">Menu item</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item text-center" href="#">Menu item</a>
                            </li>
                        </ul>
                    </div>

                </ul>
            </div>
        </div>
    </nav>
</header>

WebSistemaVentas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebSistemaVentas</title>
    <link rel="stylesheet" href="~/css/iziToast.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebSistemaVentas.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/header.css"/>

    @await RenderSectionAsync("Styles", required: false)

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.4/css/tether.min.css">

    <script src="~/js/iziToast.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.4/js/tether.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/2.3.1/list.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/util.js"></script>
    <script src="~/js/core.js"></script>

</head>
<body>
<partial name="_Header"/>
<div class="container">
    <main role="main" class="pb-3">
        @* <partial name="_Sidebar"/>  *@

        @RenderBody()

    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - WebSistemaVentas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@* <script src="~/js/sidebar.js"></script> *@
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebSistemaVentas/Views/Shared/_Sidebar.cshtml
@* <div id="wrapper"> *@
@*     <div class="overlay"></div> *@
@* *@
@*     <!-- Sidebar --> *@
@*     <nav class="navbar navbar-inverse fixed-top" id="sidebar-wrapper" role="navigation"> *@
@*         <ul class="nav sidebar-nav"> *@
@*             <div class="sidebar-header"> *@
@*                 <div class="sidebar-brand"> *@
@*                     <a href="#">Brand</a> *@
@*                 </div> *@
@*             </div> *@
@*             <li> *@
@*                 <a href="#home" id="btnInicio">Inicio</a> *@
@*             </li> *@
@*             <li> *@
@*                 <a href="#about">About</a> *@
@*             </li> *@
@*             <li> *@
@*                 <a href="#events">Events</a> *@
@*             </li> *@
@*             <li> *@
@*                 <a href="#team">Team</a> *@
@*             </li> *@
@*             <li class="dropdown"> *@
@*                 <a href="#works" class="dropdown-toggle" data-bs-toggle="dropdown">Works<span class="caret"></span></a> *@
@*                 <ul class="dropdown-menu animated fadeInLeft" role="menu"> *@
@*                     <div class="dropdown-header">Dropdown heading</div> *@
@*                     <li> *@
@*                         <a href="#pictures">Pictures</a> *@
@*                     </li> *@
@*                     <li> *@
@*                         <a href="@Url.Action("RegistrarCategoria", "Mantenimientos")">Videos</a> *@
@*                     </li> *@
@*                     <li> *@
@*                         <a href="#books">Books</a> *@
@*                     </li> *@
@*                     <li> *@
@*                         <a href="#art">Art</a> *@
@*                     </li> *@
@*                     <li> *@
@*                         <a href="#awards">Awards</a> *@
@*                     </li> *@
@*                 </ul> *@
@*             </li> *@
@*             <li class="dropdown"> *@
@*                 <a href="#mantenimientos" class="dropdown-toggle" data-bs-toggle="dropdown">Mantenimientos<span class="caret"></span></a> *@
@*                 <ul class="dropdown-menu animated fadeInLeft"> *@
@*                     <div class="dropdown-header">Categorías</div> *@
@*                     <li> *@
@*                         <a asp-controller="Mantenimientos" asp-action="RegistrarCategoria">Registrar Categoría</a> *@
@*                     </li> *@
@*                     <li> *@
@*                         <a asp-controller="Mantenimientos" asp-action="ListarCategorias">Listar Categorías</a> *@
@*                     </li> *@
@*                 </ul> *@
@*                 <ul class="dropdown-menu animated fadeInLeft"> *@
@*                     <div class="dropdown-header">Productos</div> *@
@*                     <li> *@
@*                         <a asp-controller="Mantenimientos" asp-action="">Registrar Producto</a> *@
@*                     </li> *@
@*                     <li> *@
@*                         <a asp-controller="Mantenimientos" asp-action="">Listar Productos</a> *@
@*                     </li> *@
@*                 </ul> *@
@*             </li> *@
@*             <li> *@
@*                 <a href="#contact">Contact</a> *@
@*             </li> *@
@*             <li> *@
@*                 <a href="#followme">Follow me</a> *@
@*             </li> *@
@*         </ul> *@
@*     </nav> *@
@*     <!-- /#sidebar-wrapper --> *@
@* *@
@*     <!-- Page Content --> *@
@*     <div id="page-content-wrapper"> *@
@*         <button type="button" class="hamburger animated fadeInLeft is-closed" data-toggle="offcanvas"> *@
@*             <span class="hamb-top"></span> *@
@*             <span class="hamb-middle"></span> *@
@*             <span class="hamb-bottom"></span> *@
@*         </button> *@
@*         <div class="container"> *@
@*             <div class="row"> *@
@*                 <div class="col-lg-8 col-lg-offset-2"> *@
@*                 </div> *@
@*             </div> *@
@*         </div> *@
@*     </div> *@
@*     <!-- /#page-content-wrapper --> *@
@* *@
@* </div> *@
@* <!-- /#wrapper --> *@